"""new table for teams and seasons

Revision ID: 4ea87909fce2
Revises: 8727bf09e7dd
Create Date: 2024-11-15 23:25:07.108427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4ea87909fce2'
down_revision: Union[str, None] = '8727bf09e7dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teamseason',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('season_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['season_name'], ['season.name'], ),
    sa.ForeignKeyConstraint(['team_name'], ['team.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teamseason')
    # ### end Alembic commands ###
