"""Initial migration

Revision ID: 577532adc254
Revises: 
Create Date: 2024-09-05 16:40:13.851780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '577532adc254'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referee',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_referee_name'), 'referee', ['name'], unique=True)
    op.create_table('season',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_season_name'), 'season', ['name'], unique=True)
    op.create_table('team',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=True)
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('division', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_date', sa.Date(), nullable=False),
    sa.Column('match_time', sa.Time(), nullable=False),
    sa.Column('home_team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('away_team_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referee_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_time_home_goals', sa.Integer(), nullable=False),
    sa.Column('full_time_away_goals', sa.Integer(), nullable=False),
    sa.Column('full_time_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('half_time_home_goals', sa.Integer(), nullable=False),
    sa.Column('half_time_away_goals', sa.Integer(), nullable=False),
    sa.Column('half_time_result', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.Column('bet365_home_win_odds', sa.Float(), nullable=True),
    sa.Column('bet365_draw_odds', sa.Float(), nullable=True),
    sa.Column('bet365_away_win_odds', sa.Float(), nullable=True),
    sa.Column('bet_and_win_home_win_odds', sa.Float(), nullable=True),
    sa.Column('bet_and_win_draw_odds', sa.Float(), nullable=True),
    sa.Column('bet_and_win_away_win_odds', sa.Float(), nullable=True),
    sa.Column('interwetten_home_win_odds', sa.Float(), nullable=True),
    sa.Column('interwetten_draw_odds', sa.Float(), nullable=True),
    sa.Column('interwetten_away_win_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_home_win_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_draw_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_away_win_odds', sa.Float(), nullable=True),
    sa.Column('william_hill_home_win_odds', sa.Float(), nullable=True),
    sa.Column('william_hill_draw_odds', sa.Float(), nullable=True),
    sa.Column('william_hill_away_win_odds', sa.Float(), nullable=True),
    sa.Column('vc_bet_home_win_odds', sa.Float(), nullable=True),
    sa.Column('vc_bet_draw_odds', sa.Float(), nullable=True),
    sa.Column('vc_bet_away_win_odds', sa.Float(), nullable=True),
    sa.Column('max_home_win_odds', sa.Float(), nullable=True),
    sa.Column('max_draw_odds', sa.Float(), nullable=True),
    sa.Column('max_away_win_odds', sa.Float(), nullable=True),
    sa.Column('avg_home_win_odds', sa.Float(), nullable=True),
    sa.Column('avg_draw_odds', sa.Float(), nullable=True),
    sa.Column('avg_away_win_odds', sa.Float(), nullable=True),
    sa.Column('bet365_over_2_5_odds', sa.Float(), nullable=True),
    sa.Column('bet365_under_2_5_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_over_2_5_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_under_2_5_odds', sa.Float(), nullable=True),
    sa.Column('max_over_2_5_odds', sa.Float(), nullable=True),
    sa.Column('max_under_2_5_odds', sa.Float(), nullable=True),
    sa.Column('avg_over_2_5_odds', sa.Float(), nullable=True),
    sa.Column('avg_under_2_5_odds', sa.Float(), nullable=True),
    sa.Column('asian_handicap_line', sa.Float(), nullable=True),
    sa.Column('bet365_asian_handicap_home_odds', sa.Float(), nullable=True),
    sa.Column('bet365_asian_handicap_away_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_asian_handicap_home_odds', sa.Float(), nullable=True),
    sa.Column('pinnacle_asian_handicap_away_odds', sa.Float(), nullable=True),
    sa.Column('max_asian_handicap_home_odds', sa.Float(), nullable=True),
    sa.Column('max_asian_handicap_away_odds', sa.Float(), nullable=True),
    sa.Column('avg_asian_handicap_home_odds', sa.Float(), nullable=True),
    sa.Column('avg_asian_handicap_away_odds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['away_team_name'], ['team.name'], ),
    sa.ForeignKeyConstraint(['home_team_name'], ['team.name'], ),
    sa.ForeignKeyConstraint(['referee_name'], ['referee.name'], ),
    sa.ForeignKeyConstraint(['season_name'], ['season.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_season_name'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_referee_name'), table_name='referee')
    op.drop_table('referee')
    # ### end Alembic commands ###
