"""added stadiums

Revision ID: 8727bf09e7dd
Revises: b802f50cf094
Create Date: 2024-11-15 22:49:01.025362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8727bf09e7dd'
down_revision: Union[str, None] = 'b802f50cf094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stadium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('home_team', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['home_team'], ['team.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stadium_name'), 'stadium', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stadium_name'), table_name='stadium')
    op.drop_table('stadium')
    # ### end Alembic commands ###
