"""optional half time

Revision ID: b802f50cf094
Revises: e26340cef275
Create Date: 2024-09-08 12:14:35.851810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b802f50cf094'
down_revision: Union[str, None] = 'e26340cef275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'half_time_home_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'half_time_away_goals',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('match', 'half_time_result',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'half_time_result',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('match', 'half_time_away_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('match', 'half_time_home_goals',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
