"""Make time an optional parameter

Revision ID: e26340cef275
Revises: 93b45104af8e
Create Date: 2024-09-08 10:29:46.703002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e26340cef275'
down_revision: Union[str, None] = '93b45104af8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'match_time',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'match_time',
               existing_type=postgresql.TIME(),
               nullable=False)
    # ### end Alembic commands ###
