name: Fly Deploy to Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy ./backend --config fly.production.toml --remote-only 
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          ENVIRONMENT: production
          BACKEND_CORS_ORIGIN: ${{ secrets.BACKEND_CORS_ORIGIN }}
          PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
          POSTGRES_SERVER: ${{ secrets.PROD_PG_SERVER }}
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ secrets.PROD_PG_DB }}
          POSTGRES_USER: ${{ secrets.PROD_PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.PROD_PG_PASSWORD }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
