name: Fly Deploy to Review
on:
  push:
    branches:
      - master    # change to main if needed
jobs:
  deploy:
    name: Deploy app
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}
    steps: 
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: fly deploy --config ./backend/fly.staging.toml --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          POSTGRES_SERVER: ${{ secrets.STAGING_PG_SERVER }}
          POSTGRES_PORT: 5432
          POSTGRES_DB: ${{ secrets.STAGING_PG_DB }}
          POSTGRES_USER: ${{ secrets.STAGING_PG_USER }}
          POSTGRES_PASSWORD: ${{ secrets.STAGING_PG_PASSWORD }}
